defaults_development: &defaults_development
 adapter: mysql2
 encoding: utf8
 host: localhost
 username: shop
 password: shop

development:
 database: shop
 <<: *defaults_development

#test:
# database: application_test
# <<: *defaults_development
#
#cucumber:
# database: application_test
# <<: *defaults_development

